export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_PASSED = "LOGIN_USER_PASSED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const USER_LOGGED = "USER_LOGGED";
export const LOGOUT_USER = "LOGOUT_USER";
